services:
  - type: web
    name: seedloaf-discord-bot
    runtime: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "python main.py"
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: SEEDLOAF_EMAIL
        sync: false
      - key: SEEDLOAF_PASSWORD
        sync: false
